### **Overview**

Dear Learner, 

Congratulations, you have studied NumPy all the way through the end of this bootcamp!!! This is the final graded hands-on exercise where you will be accomplishing the below mentioned task.

**Author:** Avantika Podar

# Task 1:   

Construct a random 3x28x28 NumPy array called *original* to represent an image and then convert this into into a 1x(3x28x28) array called *flat*. This converts it into a single row of pixels. Next, convert this to a 1D array (flatten the array using flat.flatten()). Print shape of all arrays. You may use the random function to generate the array.



In [1]:
import numpy as np
original = np.random.randint(0, 100, size=(3, 28, 28)) #create 3d array

In [2]:
original 

array([[[66, 89, 12, ..., 78, 71, 99],
        [16, 93, 11, ...,  2, 11, 80],
        [ 7, 65,  9, ..., 26,  4, 42],
        ...,
        [59, 77, 94, ..., 82, 98, 75],
        [46, 95, 52, ..., 49, 21, 90],
        [25, 10, 99, ..., 61, 47, 30]],

       [[42, 64, 48, ..., 93,  3, 97],
        [54, 92, 62, ..., 55, 80, 29],
        [ 3, 19, 41, ..., 62, 29, 60],
        ...,
        [17, 47, 95, ..., 83, 29, 54],
        [68, 41, 28, ..., 83, 88, 89],
        [98, 94, 39, ...,  1, 47, 75]],

       [[ 3, 80, 97, ..., 61, 46, 95],
        [28, 88, 27, ..., 18, 41, 45],
        [77, 43, 80, ..., 70, 69, 63],
        ...,
        [14, 83, 93, ..., 11, 22, 73],
        [58, 95, 63, ...,  5, 76,  6],
        [18, 15, 34, ..., 66, 64, 12]]])

In [3]:
flat=original.flatten() #flatten 3d array to 1d array

In [4]:
flat

array([66, 89, 12, ..., 66, 64, 12])

In [5]:
original.shape #shape of 3d array

(3, 28, 28)

In [6]:
flat.shape #shape of 1d array

(2352,)

# Task 2: Print out the following: 
  * dimension of the arrays.
  * memory address of the arrays (pointer).
  * shape of the arrays.
  * data types of the arrays. 




In [7]:
#dimension of arrays
original.ndim 

3

In [8]:
flat.ndim 

1

In [9]:
#pointer of arrays
original[1,6,17] 

92

In [10]:
flat[3] 

42

In [11]:
#shape of the arrays.
original.shape 

(3, 28, 28)

In [12]:
flat.shape

(2352,)

In [13]:
#data types of the arrays.
original.dtype

dtype('int32')

In [14]:
flat.dtype

dtype('int32')

# Task 3: 
Construct a new array which is a negative of the *original* array, i.e, all elements are negative of those in the *original* array. Print the new array. Add the original and new arrays. Print the result. 

In [15]:
neg_original=np.negative(original) #new array which is a negative of the original array

In [16]:
neg_original 

array([[[-66, -89, -12, ..., -78, -71, -99],
        [-16, -93, -11, ...,  -2, -11, -80],
        [ -7, -65,  -9, ..., -26,  -4, -42],
        ...,
        [-59, -77, -94, ..., -82, -98, -75],
        [-46, -95, -52, ..., -49, -21, -90],
        [-25, -10, -99, ..., -61, -47, -30]],

       [[-42, -64, -48, ..., -93,  -3, -97],
        [-54, -92, -62, ..., -55, -80, -29],
        [ -3, -19, -41, ..., -62, -29, -60],
        ...,
        [-17, -47, -95, ..., -83, -29, -54],
        [-68, -41, -28, ..., -83, -88, -89],
        [-98, -94, -39, ...,  -1, -47, -75]],

       [[ -3, -80, -97, ..., -61, -46, -95],
        [-28, -88, -27, ..., -18, -41, -45],
        [-77, -43, -80, ..., -70, -69, -63],
        ...,
        [-14, -83, -93, ..., -11, -22, -73],
        [-58, -95, -63, ...,  -5, -76,  -6],
        [-18, -15, -34, ..., -66, -64, -12]]])

In [17]:
#addition of original and negative of the original array
sum = original + neg_original

In [18]:
sum

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]])

# Task 4

A 3x28x28 basically means 28x28 matrices repeated three times. How would you access the first 10 elements of the 2nd row of the second 28x28 matrix? Consider the original array for this. Print the elements.

In [19]:
#first 10 elements of the 2nd row of the second 28x28 matrix
original[1,1,0:10]

array([54, 92, 62, 74, 88, 17, 61, 11, 82, 33])

# Task 5 (Optional)
A 3x28x28 image means 3 channels of Red, Green, or Blue (Popularly known as RGB image). Each color channel has a height and width, which is 28X28 in this case. The entire picture can represented through this method. Print the shape of the Blue pixel matrix and its first 3 rows.

In [20]:
original[2,0:3,:]

array([[ 3, 80, 97, 37, 99, 56, 99, 31, 39, 12, 26, 66, 69, 87, 31, 14,
        32, 12, 56, 22, 36, 93, 83, 64,  3, 61, 46, 95],
       [28, 88, 27, 71, 93, 23, 55, 66, 53, 98,  1, 77,  6, 36, 89, 17,
         7, 41, 76, 92, 22,  9, 16, 45, 89, 18, 41, 45],
       [77, 43, 80, 35, 59, 40, 66,  3, 26, 10, 90, 63, 68, 30, 73, 13,
        44, 96,  3, 39, 99, 11, 51, 33, 42, 70, 69, 63]])

# Task 6 
Create a 1 dimensional numpy array of the first 50 even numbers. Convert this to a 10x5 numpy array and print its transpose. 

In [21]:
list=[]
i=1
while len(list)!=50:
    if i%2==0:
        list.append(i)
        i=i+1
    else:
        i=i+1


In [22]:
list

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [23]:
len(list)

50

In [24]:
even_arr=np.array(list) #1 dimensional numpy array of the first 50 even numbers.

In [25]:
even_arr

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [26]:
#Convert this to a 10x5 numpy array 
reshape_even_arr = even_arr.reshape(10,5)
reshape_even_arr

array([[  2,   4,   6,   8,  10],
       [ 12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50],
       [ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

In [27]:
#transpose
np.transpose(reshape_even_arr)

array([[  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

# Task 7 
Consider the 10x5 array created in Task 6. Find the mean of each row and column. You may use in built functions or write your own code.

In [28]:
np.mean(reshape_even_arr,axis=0) #mean of each columns 

array([47., 49., 51., 53., 55.])

In [29]:
np.mean(reshape_even_arr,axis=1) #mean of each rows

array([ 6., 16., 26., 36., 46., 56., 66., 76., 86., 96.])

# Task 8
Can we create a 3x3 array of the first 50 even numbers? Why or why not? What are other values of m and n for which mxn dimension is allowed for 50 elements?

In [30]:
even_arr.reshape(3,3)

ValueError: cannot reshape array of size 50 into shape (3,3)

In [31]:
even_arr.shape

(50,)

- NO we cannot create a 3x3 array of the first 50 even numbers. Because 3x3 array in 1D means shape(9,) whereas for first 50 even numbers, shape in 1d is shape(50,). 
- other values of m and n for which mxn dimension is allowed for 50 elements are : 2x4, 1x3, 4x6, 6x3, etc. Hence the multiple of m and n must result 50 to make make mxn dimension of 50 elements. 
